# Generated by Django 5.2 on 2025-04-16 17:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('twitter', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('organization_name', models.CharField(blank=True, max_length=255, null=True)),
                ('organization_id', models.CharField(blank=True, max_length=255, null=True)),
                ('hunter_confidence', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('hunter_type', models.CharField(blank=True, max_length=50, null=True)),
                ('hunter_sources', models.TextField(blank=True, null=True)),
                ('hunter_seniority', models.CharField(blank=True, max_length=50, null=True)),
                ('hunter_department', models.CharField(blank=True, max_length=100, null=True)),
                ('verification_status', models.CharField(blank=True, max_length=50, null=True)),
                ('verification_date', models.DateField(blank=True, null=True)),
                ('apollo_id', models.CharField(blank=True, max_length=255, null=True)),
                ('apollo_contact_roles', models.TextField(blank=True, null=True)),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('headline', models.TextField(blank=True, null=True)),
                ('present_raw_address', models.TextField(blank=True, null=True)),
                ('email_status', models.CharField(blank=True, max_length=100, null=True)),
                ('email_true_status', models.CharField(blank=True, max_length=100, null=True)),
                ('email_source', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('original_source', models.CharField(blank=True, max_length=100, null=True)),
                ('zerobounce_status', models.CharField(blank=True, choices=[('valid', 'Valid'), ('invalid', 'Invalid'), ('catch-all', 'Catch-All'), ('unknown', 'Unknown'), ('spamtrap', 'Spam Trap'), ('abuse', 'Abuse'), ('do_not_mail', 'Do Not Mail'), ('unverified', 'Unverified')], default='unverified', max_length=50, null=True)),
                ('zerobounce_sub_status', models.CharField(blank=True, choices=[('', 'None'), ('alternate', 'Alternate'), ('antispam_system', 'Antispam System'), ('greylisted', 'Greylisted'), ('mail_server_temporary_error', 'Mail Server Temporary Error'), ('forcible_disconnect', 'Forcible Disconnect'), ('mail_server_did_not_respond', 'Mail Server Did Not Respond'), ('timeout_exceeded', 'Timeout Exceeded'), ('failed_smtp_connection', 'Failed SMTP Connection'), ('mailbox_quota_exceeded', 'Mailbox Quota Exceeded'), ('exception_occurred', 'Exception Occurred'), ('possible_trap', 'Possible Trap'), ('role_based', 'Role Based'), ('global_suppression', 'Global Suppression'), ('mailbox_not_found', 'Mailbox Not Found'), ('no_dns_entries', 'No DNS Entries'), ('failed_syntax_check', 'Failed Syntax Check'), ('possible_typo', 'Possible Typo'), ('unroutable_ip_address', 'Unroutable IP Address'), ('leading_period_removed', 'Leading Period Removed'), ('does_not_accept_mail', 'Does Not Accept Mail'), ('alias_address', 'Alias Address'), ('role_based_catch_all', 'Role Based Catch All'), ('disposable', 'Disposable'), ('toxic', 'Toxic')], default='', max_length=50, null=True)),
                ('zerobounce_free_email', models.BooleanField(blank=True, null=True)),
                ('zerobounce_did_you_mean', models.CharField(blank=True, max_length=255, null=True)),
                ('zerobounce_domain_age_days', models.IntegerField(blank=True, null=True)),
                ('zerobounce_active_in_days', models.CharField(blank=True, max_length=50, null=True)),
                ('zerobounce_smtp_provider', models.CharField(blank=True, max_length=100, null=True)),
                ('zerobounce_mx_record', models.CharField(blank=True, max_length=255, null=True)),
                ('zerobounce_mx_found', models.BooleanField(blank=True, null=True)),
                ('zerobounce_country', models.CharField(blank=True, max_length=100, null=True)),
                ('zerobounce_region', models.CharField(blank=True, max_length=100, null=True)),
                ('zerobounce_city', models.CharField(blank=True, max_length=100, null=True)),
                ('zerobounce_zipcode', models.CharField(blank=True, max_length=20, null=True)),
                ('zerobounce_processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_activity_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('sent', 'Sent'), ('replied', 'Replied'), ('unsubscribed', 'Unsubscribed')], default='new', max_length=50)),
                ('source_channel', models.CharField(choices=[('scraped', 'Scraped'), ('hunter', 'Hunter'), ('apollo', 'Apollo'), ('manual', 'Manual')], default='scraped', max_length=50)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='companies.company')),
                ('contact_lists', models.ManyToManyField(blank=True, related_name='contacts', to='contacts.contactlist')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'indexes': [models.Index(fields=['email'], name='contacts_co_email_25f973_idx'), models.Index(fields=['organization_id'], name='contacts_co_organiz_cdf98d_idx'), models.Index(fields=['apollo_id'], name='contacts_co_apollo__38c17d_idx'), models.Index(fields=['zerobounce_status'], name='contacts_co_zerobou_540a6a_idx')],
            },
        ),
    ]
