# Generated by Django 5.2 on 2025-04-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='apollo_contact_roles',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='hunter_sources',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
