# Generated by Django 5.2 on 2025-04-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_cohort'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='exclude_unverified',
            field=models.BooleanField(default=False, help_text='Whether to exclude contacts that have never been verified'),
        ),
        migrations.AddField(
            model_name='cohort',
            name='include_verification_statuses',
            field=models.JSONField(blank=True, default=list, help_text='List of verification statuses to include (empty means include all)'),
        ),
        migrations.AddField(
            model_name='cohort',
            name='include_verification_substatuses',
            field=models.JSONField(blank=True, default=list, help_text='List of verification sub-statuses to include (empty means include all)'),
        ),
    ]
