# Generated by Django 5.2 on 2025-04-29 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_alter_contact_first_name_alter_contact_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cohort',
            name='contacts',
        ),
        migrations.AddField(
            model_name='contact',
            name='cohort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='contacts.cohort'),
        ),
    ]
