services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_web_leads
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
  
  huey:
    build: .
    command: python manage.py run_huey
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_started
    restart: unless-stopped

  db:
    image: postgres:17.4
    volumes:
      - postgres_data_leads:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"


volumes:
  postgres_data_leads: