# Generated by Django 5.2 on 2025-04-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deal',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='dealstage',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='deal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='manual_conversion_probability',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
