# Generated by Django 5.2 on 2025-04-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_alter_deal_options_alter_dealstage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='margin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
