# Generated by Django 5.2 on 2025-04-16 17:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('serp_position', models.IntegerField(blank=True, null=True)),
                ('place_id', models.CharField(blank=True, max_length=255, null=True)),
                ('data_id', models.CharField(blank=True, max_length=255, null=True)),
                ('data_cid', models.CharField(blank=True, max_length=255, null=True)),
                ('provider_id', models.CharField(blank=True, max_length=255, null=True)),
                ('rating', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('reviews_count', models.IntegerField(blank=True, null=True)),
                ('primary_type', models.CharField(blank=True, max_length=255, null=True)),
                ('types', models.TextField(blank=True, null=True)),
                ('type_ids', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('dine_in_available', models.BooleanField(default=False)),
                ('takeout_available', models.BooleanField(default=False)),
                ('no_contact_delivery_available', models.BooleanField(default=False)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('apollo_id', models.CharField(blank=True, max_length=255, null=True)),
                ('blog_url', models.URLField(blank=True, null=True)),
                ('angellist_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('languages', models.TextField(blank=True, null=True)),
                ('alexa_ranking', models.IntegerField(blank=True, null=True)),
                ('linkedin_uid', models.CharField(blank=True, max_length=50, null=True)),
                ('founded_year', models.IntegerField(blank=True, null=True)),
                ('publicly_traded_symbol', models.CharField(blank=True, max_length=20, null=True)),
                ('publicly_traded_exchange', models.CharField(blank=True, max_length=50, null=True)),
                ('crunchbase_url', models.URLField(blank=True, null=True)),
                ('primary_domain', models.CharField(blank=True, max_length=255, null=True)),
                ('intent_strength', models.FloatField(blank=True, null=True)),
                ('show_intent', models.BooleanField(default=True)),
                ('has_intent_signal_account', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_lists', models.ManyToManyField(blank=True, related_name='companies', to='companies.companylist')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'indexes': [models.Index(fields=['name'], name='companies_c_name_2d8260_idx'), models.Index(fields=['place_id'], name='companies_c_place_i_c6af7f_idx'), models.Index(fields=['apollo_id'], name='companies_c_apollo__dc6617_idx'), models.Index(fields=['domain'], name='companies_c_domain_99e280_idx')],
            },
        ),
    ]
