# Generated by Django 5.2 on 2025-04-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_city_company_state_company_state_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='thumbnail_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
