# Generated by Django 5.2 on 2025-04-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_thumbnail_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='website_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
