# Generated by Django 5.2 on 2025-04-16 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('results_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CompanySearch',
            fields=[
                ('search_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finder.search')),
                ('method', models.CharField(choices=[('serpapi', 'SerpAPI'), ('apollo', 'Apollo')], default='serpapi', max_length=10)),
                ('companies', models.ManyToManyField(blank=True, related_name='company_searches', to='companies.company')),
            ],
            options={
                'verbose_name': 'Company Search',
                'verbose_name_plural': 'Company Searches',
            },
            bases=('finder.search',),
        ),
        migrations.CreateModel(
            name='ContactSearch',
            fields=[
                ('search_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finder.search')),
                ('method', models.CharField(choices=[('apollo', 'Apollo'), ('hunter', 'Hunter'), ('scrape', 'Scrape')], default='hunter', max_length=10)),
                ('contacts', models.ManyToManyField(blank=True, related_name='contact_searches', to='contacts.contact')),
            ],
            options={
                'verbose_name': 'Contact Search',
                'verbose_name_plural': 'Contact Searches',
            },
            bases=('finder.search',),
        ),
        migrations.CreateModel(
            name='SerpAPISearchParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_term', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('zoom', models.IntegerField(default=10)),
                ('max_results', models.IntegerField(default=100)),
                ('enrich', models.BooleanField(default=False)),
                ('company_search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serpapi_search_params', to='finder.companysearch')),
            ],
            options={
                'verbose_name': 'SerpAPI Search Parameters',
                'verbose_name_plural': 'SerpAPI Search Parameters',
            },
        ),
        migrations.CreateModel(
            name='ApolloCompanySearchParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apollo_company_search_params', to='finder.companysearch')),
            ],
        ),
        migrations.CreateModel(
            name='WebScrapeSearchParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.IntegerField(default=1)),
                ('max_results', models.IntegerField(default=10)),
                ('contact_search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_scrape_search_params', to='finder.contactsearch')),
            ],
        ),
        migrations.CreateModel(
            name='HunterDomainSearchParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('generic', 'Generic'), ('personal', 'Personal'), ('all', 'All')], default='all', max_length=10)),
                ('max_results', models.IntegerField(default=10)),
                ('contact_search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hunter_domain_search_params', to='finder.contactsearch')),
            ],
        ),
        migrations.CreateModel(
            name='ApolloContactSearchParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apollo_contact_search_params', to='finder.contactsearch')),
            ],
        ),
    ]
