# Generated by Django 5.2 on 2025-04-23 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_cohort'),
        ('finder', '0003_serpapisearchparameters_place_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailValidationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name for this validation batch', max_length=255)),
                ('task_id', models.CharField(blank=True, help_text='Huey task ID', max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('max_validations', models.IntegerField(blank=True, help_text='Maximum validations to perform', null=True)),
                ('use_ip', models.BooleanField(default=True, help_text='Include IP addresses in validation')),
                ('timeout', models.IntegerField(default=10, help_text='API timeout in seconds')),
                ('valid_count', models.IntegerField(default=0, help_text='Number of valid emails')),
                ('invalid_count', models.IntegerField(default=0, help_text='Number of invalid emails')),
                ('catch_all_count', models.IntegerField(default=0, help_text='Number of catch-all emails')),
                ('unknown_count', models.IntegerField(default=0, help_text='Number of unknown emails')),
                ('other_count', models.IntegerField(default=0, help_text='Number of other emails')),
                ('error_count', models.IntegerField(default=0, help_text='Number of errors')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('contact_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_batches', to='contacts.contactlist')),
            ],
        ),
    ]
